#goal definition
control_msgs/FollowJointTrajectoryActionGoal  goal
---
#result definition
control_msgs/FollowJointTrajectoryActionResult  result
---
#feedback
control_msgs/FollowJointTrajectoryActionFeedback feedback
